### ISSUE TITLE
bug: panic in `safe.ID` and reflection issue

### ISSUE THREAD

**Issue by pelageech** [ydb-platform/ydb-go-sdk-otel#25]
# Bug Report

**YDB GO SDK OpenTelemetry adapter version:**
0.7.8

**Environment**
macOS Sonoma 14.2.1 amd64

**Current behavior:**
```
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: panic: reflect: call of reflect.Value.IsNil on string Value
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: goroutine 274 [[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: running]:
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: reflect.Value.IsNil(...[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: )
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 	/usr/local/Cellar/go/1.22.6/libexec/src/reflect/value.go:[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 1574[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: github.com/ydb-platform/ydb-go-sdk-otel/internal/safe.ID({0x569db0d8?, 0xe419210?}[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: )
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 	/Users/artblaginin/go/src/bb.yandexcloud.net/cloud/cloud-go/vendor/github.com/ydb-platform/ydb-go-sdk-otel/internal/safe/safe.go:62 +0x11e
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: github.com/ydb-platform/ydb-go-sdk-otel.query.func23.1({{0x0?, 0x0?}, {0xe425560?, 0xe419210?}})
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 	/Users/artblaginin/go/src/bb.yandexcloud.net/cloud/cloud-go/vendor/github.com/ydb-platform/ydb-go-sdk-otel/query.go:394 +0x86
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: github.com/ydb-platform/ydb-go-sdk/v3/trace.(*Query).Compose.func23.2({{0x0?, 0x0?}[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: , {[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0xe425560?, 0xe419210?}})
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 	[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: /Users/artblaginin/go/src/bb.yandexcloud.net/cloud/cloud-go/vendor/github.com/ydb-platform/ydb-go-sdk/v3/trace/query_gtrace.go:822 +0xd3
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: github.com/ydb-platform/ydb-go-sdk/v3/trace.(*Query).Compose.func23.2([loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: {[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: {[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0x0[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: ?[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: , [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0x0[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: ?[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: }[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: , {0xe425560?[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: , [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0xe419210[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: ?[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: }[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: }[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: )
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 	/Users/artblaginin/go/src/bb.yandexcloud.net/cloud/cloud-go/vendor/github.com/ydb-platform/ydb-go-sdk/v3/trace/query_gtrace.go:[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 819 +[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0xa6
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: github.com/ydb-platform/ydb-go-sdk/v3/trace.(*Query).Compose.func23.2({{0x0?[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: , 0x0?}, {0xe425560[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: ?[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: , [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0xe419210?}[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: }[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: )
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 	/Users/artblaginin/go/src/bb.yandexcloud.net/cloud/cloud-go/vendor/github.com/ydb-platform/ydb-go-sdk/v3/trace/query_gtrace.go:819 +0xa6
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: github.com/ydb-platform/ydb-go-sdk/v3/trace.QueryOnSessionBegin.func1([loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: {0x0?, 0x0[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: ?}[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: , [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: {[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0xe425560[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: ?[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: , [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0xe419210[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: ?[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: }[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: )
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 	/Users/artblaginin/go/src/bb.yandexcloud.net/cloud/cloud-go/vendor/github.com/ydb-platform/ydb-go-sdk/v3/trace/query_gtrace.go:1853 +0x2b[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: github.com/ydb-platform/ydb-go-sdk/v3/internal/query.(*Session).Begin.func1[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: ()
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 	/Users/artblaginin/go/src/bb.yandexcloud.net/cloud/cloud-go/vendor/github.com/ydb-platform/ydb-go-sdk/v3/internal/query/session.go:[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 256 +0x31
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: github.com/ydb-platform/ydb-go-sdk/v3/internal/query.(*Session).Begin([loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0xc000bfeaa0, {0xe438350, 0xc000858c00}, {0xc0007103e0, [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0x1[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: , [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0x1[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: }[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: )
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 	/Users/artblaginin/go/src/bb.yandexcloud.net/cloud/cloud-go/vendor/github.com/ydb-platform/ydb-go-sdk/v3/internal/query/session.go:259 +0x1dc[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: github.com/ydb-platform/ydb-go-sdk/v3/internal/query.doTx.func1([loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: {0xe438350, 0xc000858c00}, 0xc000859f80?)
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 	/Users/artblaginin/go/src/bb.yandexcloud.net/cloud/cloud-go/vendor/github.com/ydb-platform/ydb-go-sdk/v3/internal/query/client.go:367 +0x4f
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: github.com/ydb-platform/ydb-go-sdk/v3/internal/query.do.func1[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: ({[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0xe438350[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: ?[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: , [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0xc000858c00[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: ?[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: }[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: , [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0xc000bfeaa0[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: )
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 	/Users/artblaginin/go/src/bb.yandexcloud.net/cloud/cloud-go/vendor/github.com/ydb-platform/ydb-go-sdk/v3/internal/query/client.go:314 +0x33
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: github.com/ydb-platform/ydb-go-sdk/v3/internal/query.(*poolStub).With.func1({0xe438350[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: , 0xc000858c00})
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 	/Users/artblaginin/go/src/bb.yandexcloud.net/cloud/cloud-go/vendor/github.com/ydb-platform/ydb-go-sdk/v3/internal/query/client.go:281 +0xb2[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: github.com/ydb-platform/ydb-go-sdk/v3/retry.Retry.func1[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: ([loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: {0xe438350?, [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0xc000858c00?[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: })
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 	/Users/artblaginin/go/src/bb.yandexcloud.net/cloud/cloud-go/vendor/github.com/ydb-platform/ydb-go-sdk/v3/retry/retry.go:262 +0x22
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: github.com/ydb-platform/ydb-go-sdk/v3/retry.opWithRecover[...]({0xe438350?, 0xc000858c00?[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: }, 0xc0007104a0[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: ?[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: , [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0x0[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: ?[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: )
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 	/Users/artblaginin/go/src/bb.yandexcloud.net/cloud/cloud-go/vendor/github.com/ydb-platform/ydb-go-sdk/v3/retry/retry.go:409 +0x97
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: github.com/ydb-platform/ydb-go-sdk/v3/retry.RetryWithResult[...]([loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: {0xe438350, 0xc000858ae0}, 0xc000526420, {0xc0008cc160, 0x2, 0x5677d688})
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 	/Users/artblaginin/go/src/bb.yandexcloud.net/cloud/cloud-go/vendor/github.com/ydb-platform/ydb-go-sdk/v3/retry/retry.go:341[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]:  +0x4eb
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: github.com/ydb-platform/ydb-go-sdk/v3/retry.Retry[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: ({0xe438350?, 0xc000858ae0?}[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: , [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0x0?, {0xc0008cc160[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: ?, [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0xc000b34488?[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: , 0xcda82a5[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: ?})
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 	/Users/artblaginin/go/src/bb.yandexcloud.net/cloud/cloud-go/vendor/github.com/ydb-platform/ydb-go-sdk/v3/retry/retry.go:[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 261[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]:  +[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0x54[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: github.com/ydb-platform/ydb-go-sdk/v3/internal/query.(*poolStub).With(0x0?[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: , {[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0xe438350[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: ?[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: , [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0xc000858ae0[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: ?[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: }[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: , [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0xcda82a5[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: ?[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: , [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: {[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0xc0008cc160[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: ?[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: , [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0xe217500[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: ?, 0xc000710401?})
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 	[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: /Users/artblaginin/go/src/bb.yandexcloud.net/cloud/cloud-go/vendor/github.com/ydb-platform/ydb-go-sdk/v3/internal/query/client.go:272 +0x5b
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: github.com/ydb-platform/ydb-go-sdk/v3/internal/query.do({0xe438350, 0xc000858ae0}[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: , {0xe436aa0[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: , 0xc0003f0548}, 0xc000862240, [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: {0xc0008cc160, 0x2, 0x2})
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 	/Users/artblaginin/go/src/bb.yandexcloud.net/cloud/cloud-go/vendor/github.com/ydb-platform/ydb-go-sdk/v3/internal/query/client.go:311[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]:  +0xa3[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: github.com/ydb-platform/ydb-go-sdk/v3/internal/query.doTx({0xe438350, 0xc000858ae0}, {0xe436aa0, 0xc0003f0548}, 0xc000862228, 0xc000b345d0?, {0xc000b34848?, 0xc00063c240?, [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0xb345d0[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: ?}[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: )
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 	/Users/artblaginin/go/src/bb.yandexcloud.net/cloud/cloud-go/vendor/github.com/ydb-platform/ydb-go-sdk/v3/internal/query/client.go:366[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]:  +0xec
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: github.com/ydb-platform/ydb-go-sdk/v3/internal/query.(*Client).DoTx([loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0xc000bf5dd0, {[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0xe4383f8[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: , [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0xc00051e070[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: }[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: , [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0xc00039eb80[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: , [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: {[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0xc000b34848[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: , [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0x3[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: , [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 0x3}[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: )
2024/08/22 19:56:01 [loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: 	[loadbalancer-ctrl-779572a5-b611-4d6e-9ed8-1025f5b6bbb2-1]: /Users/artblaginin/go/src/bb.yandexcloud.net/cloud/cloud-go/vendor/github.com/ydb-platform/ydb-go-sdk/v3/internal/query/client.go:593 +0x27f
```

**Expected behavior:**
No panic.

**Steps to reproduce:**
Just turn on otel for ydb and run any query.

**Other information:**
About a reflection: Isn't it overkill? How much does it cost for us when such a callback is called many times? Ofc, we should be careful with nil pointers and nil interfaces, but is a reflection a solution?

**Comment by asmyasnikov** [comment]
removed reflection in 8ac1c8bbc0c3d4bc0aa285b256961ee69a5339a7

**Comment by asmyasnikov** [comment]
fix tagged in https://github.com/ydb-platform/ydb-go-sdk-otel/releases/tag/v0.7.9
